apiVersion: v1
kind: Service
metadata:
  name: blog-go
  labels:
    app: blog-go
spec:
  type: ClusterIP  # Change to LoadBalancer if you need external access directly
  selector:
    app: blog-go
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
