name: Deploy app to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Build Go app
        run: |
          go mod tidy
          go build -o api ./cmd/api

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop the Go app service
        run: |
          ssh -o StrictHostKeyChecking=no zh@165.22.80.158 'sudo /bin/systemctl stop blog_backend.service'

      - name: Remove old API binary on VPS
        run: |
          ssh -o StrictHostKeyChecking=no zh@165.22.80.158 'rm -f /var/www/blog_backend/api'

      - name: Copy new API binary to VPS
        run: |
          scp -o StrictHostKeyChecking=no api zh@165.22.80.158:/var/www/blog_backend/

      - name: Copy source files to VPS
        run: |
          ssh -o StrictHostKeyChecking=no zh@165.22.80.158 'mkdir -p /var/www/blog_backend/src'
          scp -o StrictHostKeyChecking=no -r go.mod go.sum cmd/ internal/ zh@165.22.80.158:/var/www/blog_backend/src/
          if [ -d "pkg" ]; then scp -o StrictHostKeyChecking=no -r pkg/ zh@165.22.80.158:/var/www/blog_backend/src/; fi
          if [ -d "migrations" ]; then scp -o StrictHostKeyChecking=no -r migrations/ zh@165.22.80.158:/var/www/blog_backend/src/; fi

      - name: Restart the Go app service
        run: |
          ssh -o StrictHostKeyChecking=no zh@165.22.80.158 'sudo /bin/systemctl start blog_backend.service'

